name: Python CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  APP_PATH: ./app
  IGNORED_ERRORS: E128

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Check with Pylint
      run: pylint -Ev ${APP_PATH}
    - name: Check with Flake8
      run: flake8 --ignore=${IGNORED_ERRORS} --show-source --statistics ${APP_PATH}
    - name: Check with Mypy
      run: mypy --ignore-missing-import ${APP_PATH}