name: Python CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python@3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -f requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -f requirements-dev.txt; fi
    - name: Run Flake8
      run: |
        flake8 ./app
    - name: Run Mypy
      run: |
        mypy --ignore-missing-import ./app