name: Python CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  APP_PATH: ./app
  IGNORED_ERRORS: E128
  DEPLOY_PATH: /srv/flask

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Check with Pylint
      run: pylint -Ev ${APP_PATH}
    - name: Check with Flake8
      run: flake8 --ignore=${IGNORED_ERRORS} --show-source --statistics ${APP_PATH}
    - name: Check with Mypy
      run: mypy --ignore-missing-import ${APP_PATH}

  deploy:
    name: "Deploy to Production"
    runs-on: ubuntu-latest
    steps:
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${SSH_KEY}" > ~/.ssh/production.key
        chmod 600 ~/.ssh/production.key
        cat >>~/.ssh/config <<EOF
        Host production
          HostName ${SSH_HOST}
          User ${SSH_USER}
          Port ${SSH_PORT}
          IdentityFile ~/.ssh/production.key
          StrictHostKeyChecking no
        EOF
      env:
        SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
        SSH_PORT: ${{ secrets.PROD_SSH_PORT }}
        SSH_USER: ${{ secrets.PROD_SSH_USER }}
        SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
    - name: Stop Application Server
      run: ssh production 'sudo /bin/systemctl stop uwsgi.service'
    - name: Pull Source from Repository
      run: ssh production '/usr/bin/git -C ${DEPLOY_PATH} fetch && /usr/bin/git -C ${DEPLOY_PATH} reset --hard origin/master'
    - name: Start Application Server
      run: ssh production 'sudo /bin/systemctl start uwsgi.service'